services:
  # 1. Database Service (MongoDB)
  # Port 27017 is exposed to the host for external connections (e.g., Compass).
  mongo_dev:
    image: mongo:latest
    container_name: betterdrive_mongo_dev
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: betterdrive_db
    volumes:
      - mongodb_data:/data/db

  mongo:
    image: mongo:7
    container_name: betterdrive_mongo
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: <MONGO_INITDB_ROOT_USERNAME>
      MONGO_INITDB_ROOT_PASSWORD: <MONGO_INITDB_ROOT_PASSWORD>
      MONGO_INITDB_DATABASE: <MONGO_INITDB_DATABASE>
    volumes:
      - mongodb_data:/data/db

  # 2. API Service (Node.js API)
  api:
    image: kutsyk/betterdriver-api:latest
    container_name: betterdrive_api
    restart: on-failure
    depends_on:
      mongo:
        condition: service_started
    environment:
      MAPTILER_API_KEY: <MAPTILER_API_KEY>
      ORS_API_KEY: <ORS_API_KEY>
      MONGODB_URI: <MONGODB_URI>
      PORT: 3000 # Internal API port (used by Nginx)
      JWT_SECRET: dev_super_secret
      SWAGGER_ENABLED: true
      REQUIRE_EMAIL_VERIFICATION: false
      PUBLIC_BASE_URL: http://193.169.241.16
      GOOGLE_CLIENT_ID: your-google-client-id.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: your-google-client-secret
      GOOGLE_CALLBACK_URL: http://localhost:3000/api/v1/oauth/google/callback
      NEXT_PUBLIC_VAPID_PUBLIC_KEY: <NEXT_PUBLIC_VAPID_PUBLIC_KEY>
      VAPID_PRIVATE_KEY: <VAPID_PRIVATE_KEY>
  web:
    image: kutsyk/betterdriver-web:latest
    container_name: betterdrive_web
    restart: always
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://api:3000
      NEXT_PUBLIC_VAPID_PUBLIC_KEY: <NEXT_PUBLIC_VAPID_PUBLIC_KEY>
    expose:
      - "4200" # Expose internal port 80 (used by Nginx)

  # 4. Reverse Proxy Service (Nginx)
  nginx:
    image: nginx:latest
    container_name: betterdrive_nginx
    restart: always
    ports:
      - "80:80"
      # - "443:443" # Uncomment when you set up SSL
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - web

volumes:
  mongodb_data:
    driver: local